export const surpriseMeTexts = [
    'A group of penguins ice skating on a frozen lake under a full moon',
    'A stained glass window depicting a unicorn flying through a rainbow',
    'A surrealist portrait of a flamingo wearing a top hat and monocle',
    'A digital painting of a dragon flying over a mountain range',
    'A photo-realistic portrait of a chimpanzee wearing a bowtie and reading a newspaper',
    'A 3D rendering of a futuristic city with flying cars and neon lights',
    'A sculpture of a mermaid made entirely out of recycled plastic',
    'A painting of a lion in a forest with a castle in the background',
    'A photograph of a hummingbird hovering over a blooming flower',
    'An armchair made out of recycled skateboard decks',
    'A surreal landscape with floating islands and upside-down trees',
    'A portrait of a person made entirely out of flowers',
    'A 3D rendering of a futuristic underwater city with bioluminescent sea creatures',
    'A photograph of a person standing on the edge of a cliff with a panoramic view of the ocean',
    'A painting of a bear wearing a suit and tie and carrying a briefcase',
    'A 3D rendering of a futuristic space station orbiting a gas giant planet',
    'A surreal portrait of a person with a flamingo head and butterfly wings',
    'A photograph of a group of sea turtles swimming in crystal clear water',
    'A painting of a unicorn grazing in a meadow under a rainbow',
    'A 3D rendering of a futuristic flying saucer hovering over a city skyline',
    'A sculpture of a gorilla made entirely out of recycled car parts',
    'A photograph of a person hiking through a forest with a waterfall in the background',
    'A painting of a wolf howling at the moon',
    'A 3D rendering of a futuristic floating city with hot air balloons and airships',
    'A surreal portrait of a person with a cactus for a head',
    'A photograph of a person swimming with dolphins in the ocean',
    'A painting of a cat wearing a crown and holding a scepter',
    'A 3D rendering of a futuristic robot factory with conveyor belts and assembly lines',
    'A sculpture of an elephant made entirely out of recycled soda cans',
    'A photograph of a person watching the sunset over a desert landscape',
    'A painting of a horse galloping through a field of flowers',
    'A 3D rendering of a futuristic train station with high-speed trains and monorails',
    'A surreal portrait of a person with a clock face for a head',
    'A photograph of a person kayaking down a river with a mountain range in the background',
    'A painting of a deer in a snow-covered forest',
    'A 3D rendering of a futuristic amusement park with roller coasters and Ferris wheels',
    'A sculpture of a giraffe made entirely out of recycled glass bottles',
    'A photograph of a person sitting on a bench in a park with a city skyline in the background',
    'A painting of a hummingbird drinking nectar from a flower',
    'A 3D rendering of a futuristic laboratory with test tubes and scientific equipment',
    'A sculpture of a giraffe made entirely out of recycled glass bottles',
    'A photograph of a person sitting on a bench in a park with a city skyline in the background',
    'A painting of a hummingbird drinking nectar from a flower',
    'A 3D rendering of a futuristic laboratory with test tubes and scientific equipment',
    "A surreal portrait of a person with a bird's nest for a head",
    'A photograph of a person skiing down a mountain with snow-capped peaks in the background',
    'A painting of a butterfly perched on a leaf',
    'A 3D rendering of a futuristic space elevator stretching into the clouds'
]